### ISSUE TITLE
ValueError: CorrMM received weight with wrong type.

### ISSUE THREAD

**Issue by iiAnthony** [mikesj-public/convolutional_autoencoder#12]
Hi,

I tried your sample with, I think, latest versions of each prerequisites and got the following after fitting network correctly :
"""
(50000, 28, 28) (50000, 1, 28, 28)

2

Traceback (most recent call last):
  File "conv_autoencoder2.py", line 195, in <module>
    X_encoded = encode_input(encode_layer, X)
  File "conv_autoencoder2.py", line 193, in encode_input
    return get_output(encode_layer, inputs=X).eval()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/graph.py", line 523, in eval
    rval = self._fn_cache[inputs](*args)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 871, in __call__
    storage_map=getattr(self.fn, 'storage_map', None))
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/link.py", line 314, in raise_with_op
    reraise(exc_type, exc_value, exc_trace)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 859, in **call**
    outputs = self.fn()
ValueError: CorrMM received weight with wrong type.
Apply node that caused the error: CorrMM{(0, 0), (1, 1)}(TensorConstant{[[[[ 0.  0..0.  0.]]]]}, Subtensor{::, ::, ::int64, ::int64}.0)
Toposort index: 8
Inputs types: [TensorType(float32, (False, True, False, False)), TensorType(float64, 4D)]
Inputs shapes: [(50000, 1, 28, 28), (16, 1, 3, 3)]
Inputs strides: [(3136, 3136, 112, 4), (72, 72, -24, -8)]
Inputs values: ['not shown', 'not shown']
Outputs clients: [[Elemwise{Composite{(i0 \* (Abs((i1 + i2)) + i1 + i2))}}(TensorConstant{(1, 1, 1, 1) of 0.5}, CorrMM{(0, 0), (1, 1)}.0, InplaceDimShuffle{x,0,x,x}.0)]]

HINT: Re-running with most Theano optimization disabled could give you a back-trace of when this node was created. This can be done with by setting the Theano flag 'optimizer=fast_compile'. If that does not work, Theano optimizations can be disabled with 'optimizer=None'.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
"""

Did I miss something somewhere ?
Thanks.

**Comment by biplabdeka** [comment]
@iiAnthony were you able to figure out a solution to this? I am facing the same probelm.

**Comment by biplabdeka** [comment]
I figured it out. The computation of `X_encoded` needs to be done differently as shown below:

```
input_layer, input_layer_index = get_layer_by_name(ae, 'input0')
f = theano.function([input_layer.input_var], get_output(encode_layer))
X_encoded = f(X)
```

Got the hint from [this StackOverflow answer](http://stackoverflow.com/a/34423326).

**Comment by iiAnthony** [comment]
Hi @biplabdeka, no I did not look to deep into it.
Great !! Thank you for your hint, I'll give it a try .

**Comment by ArghyaPal** [comment]
@biplabdeka Can you make it:

input_layer, input_layer_index = get_layer_by_name(ae, 'input0')
f = theano.function([input_layer.input_var], get_output(encode_layer))
X_encoded = f(X)

more clear.. As for my case it is showing 

NameError: name 'get_layer_by_name' is not defined

Exactly what error I did..?

**Comment by mikesj-public** [comment]
@ArghyaPal : recommend that you make a pull request if you fix this.  I am no longer maintaining this project with newer versions of Lasagne, but will accept changes.

**Comment by ArghyaPal** [comment]
Finally Solved this issue:
goto your .py file and change the following snippet:

Previous:

`def get_output_from_nn(last_layer, X): #.astype(np.float32)):
    print "Here 5\n";
    indices = np.arange(128, X.shape[0], 128)
    sys.stdout.flush()

```
# not splitting into batches can cause a memory error
X_batches = np.split(X, indices)
out = []
print "Here 6\n";
for count, X_batch in enumerate(X_batches):
    out.append(last_layer.get_output(X_batch).eval())
    sys.stdout.flush()
return np.vstack(out)`
```

Now:

`def get_output_from_nn(last_layer, X): #.astype(np.float32)):
    print "Here 5\n";
    indices = np.arange(128, X.shape[0], 128)
    sys.stdout.flush()

```
# not splitting into batches can cause a memory error
X_batches = np.split(X, indices)
out = []
print "Here 6\n";
for count, X_batch in enumerate(X_batches):
    out.append(last_layer.get_output(X_batch.astype(np.float64)).eval())
    sys.stdout.flush()
return np.vstack(out)`
```
