### ISSUE TITLE
getting the error message

### ISSUE THREAD

**Issue by Ori226** [mikesj-public/convolutional_autoencoder#2]
Hi!
Great post about auto encoder! 
I had this issue when trying to run the code in ipython note book:
(BTW, I'm pretty new to python and libraries you used so the error might be a result of fault installation)

c:\anaconda\lib\lasagne-master\lasagne\init.py:86: UserWarning: The uniform initializer no longer uses Glorot et al.'s approach to determine the bounds, but defaults to the range (-0.01, 0.01) instead. Please use the new GlorotUniform initializer to get the old behavior. GlorotUniform is now the default for all layers.
  warnings.warn("The uniform initializer no longer uses Glorot et al.'s "

---

TypeError                                 Traceback (most recent call last)
<ipython-input-8-aaa2c041ef84> in <module>()
     39     verbose=1,
     40     )
---> 41 ae.fit(X_train, X_out)

C:\Anaconda\lib\site-packages\nolearn\lasagne.pyc in fit(self, X, y)
    136         out = getattr(self, '_output_layer', None)
    137         if out is None:
--> 138             out = self._output_layer = self.initialize_layers()
    139         if self.verbose:
    140             self._print_layer_info(self.get_all_layers())

C:\Anaconda\lib\site-packages\nolearn\lasagne.pyc in initialize_layers(self, layers)
    367         for (layer_name, layer_factory) in self.layers[1:]:
    368             layer_params = self._get_params_for(layer_name)
--> 369             layer = layer_factory(layer, **layer_params)
    370 
    371         self._output_layer = layer

TypeError: **init**() takes at least 3 arguments (2 given)

**Comment by mikesj-public** [comment]
Heya, sorry I don't have a lot of time to help, but I think the issue is probably with the version of lasagne you are using, they changed the parameters you have to give to some of the layers.  I would suggest that you try building the layers outside of the nolearn call so like 

lasagne.layers.Conv2DLayer(**params you want to hand in from nolearn)

and for the other layers as well until you figure out which layer is giving the bug.  Otherwise I will try and update the code this weekend!

**Comment by Ori226** [comment]
Thanks for your help, I'll try it!

**Comment by Tgaaly** [comment]
Any help with this? Seems like this code is too old for lasagne. Is there an easy fix?

I got the following error:

```
Using gpu device 0: GeForce GTX TITAN X (CNMeM is disabled)
Traceback (most recent call last):
  File "mnist_conv_autoencode.py", line 158, in <module>
    ae.fit(X_train, X_out)
  File "/home/tarek/Libraries/anaconda/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 445, in fit
    self.initialize()
  File "/home/tarek/Libraries/anaconda/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 286, in initialize
    out = self._output_layer = self.initialize_layers()
  File "/home/tarek/Libraries/anaconda/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 383, in initialize_layers
    chain_exception(TypeError(msg), e)
  File "/home/tarek/Libraries/anaconda/lib/python2.7/site-packages/nolearn/_compat.py", line 14, in chain_exception
    exec("raise exc1, None, sys.exc_info()[2]")
  File "/home/tarek/Libraries/anaconda/lib/python2.7/site-packages/nolearn/lasagne/base.py", line 378, in initialize_layers
    layer = layer_factory(**layer_kw)
  File "/home/tarek/Libraries/anaconda/lib/python2.7/site-packages/lasagne/layers/conv.py", line 391, in __init__
    super(Conv2DLayer, self).__init__(incoming, **kwargs)
TypeError: Failed to instantiate <class 'lasagne.layers.conv.Conv2DLayer'> with args {'incoming': <lasagne.layers.input.InputLayer object at 0x7fd404989a10>, 'name': 'conv', 'nonlinearity': None, 'filter_size': (7, 7), 'num_filters': 32, 'border_mode': 'valid'}.
Maybe parameter names have changed?
```

**Comment by mikesj-public** [comment]
Heya, someone has updated to latest version of lasagne, you can view and/or install version numbers for theano/nolearn/lasagne from requirements.txt

Let me know if there are any problems.

**Comment by appu0507** [comment]
Did it work with the latest version I am still getting the same error as above ?

**Comment by yshean** [comment]
I encountered this issue and removing the 'border_mode' parameter from model did the trick.

**Comment by xmuszq** [comment]
Hi yshean,

Could you give more details about how you resolve it?

**Comment by yinchuandong** [comment]
@yshean Your solution works.  @xmuszq you can refer to http://lasagne.readthedocs.org/en/latest/modules/layers/conv.html#lasagne.layers.Conv2DLayer, Here gives the parameters of Conv2DLayer. Some parameters have been updated.

**Comment by wtlim** [comment]
@yshean It works fine.
Is it a difference between lasagne v0.1 and v0.2dev1??
